datafile <- "E:/CourseraDataScience/Working Directory/household_power_consumption.txt"
data <- read.table(datafile, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
Subs <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
str(Subs)
globalActivePower <- as.numeric(Subs$Global_active_power)
globalReactivePower <- as.numeric(Subs$Global_reactive_power)
Date_Time <- strptime(paste(Subs$Date, Subs$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
subMetering1 <- as.numeric(Subs$Sub_metering_1)
subMetering2 <- as.numeric(Subs$Sub_metering_2)
subMetering3 <- as.numeric(Subs$Sub_metering_3)
voltage <- as.numeric(Subs$Voltage)
par(mfrow = c(2, 2)) 
plot(Date_Time, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(Date_Time, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(Date_Time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(Date_Time, subMetering2, type="l", col="red")
lines(Date_Time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(Date_Time, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(Date_Time, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(Date_Time, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(Date_Time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(Date_Time, subMetering2, type="l", col="red")
lines(Date_Time, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(Date_Time, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()