datafile <- "E:/CourseraDataScience/Working Directory/household_power_consumption.txt"
data <- read.table(datafile, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
Subs <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
str(Subs)
globalActivePower <- as.numeric(Subs$Global_active_power)
Date_Time <- strptime(paste(Subs$Date, Subs$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
subMetering1 <- as.numeric(Subs$Sub_metering_1)
subMetering2 <- as.numeric(Subs$Sub_metering_2)
subMetering3 <- as.numeric(Subs$Sub_metering_3)
plot(Date_Time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
lines(Date_Time, subMetering2, type="l", col="red")
lines(Date_Time, subMetering3, type="l", col="blue")
png("plot3.png", width=480, height=480)
plot(Date_Time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
lines(Date_Time, subMetering2, type="l", col="red")
lines(Date_Time, subMetering3, type="l", col="blue")
dev.off()